### ISSUE TITLE
Implement Contact Builder

### ISSUE THREAD

**Issue by DieGurke** [informatik-ag-ngl/envoy-server-standalone#35]
* Add envoy.data.server.Contact builder (Has to offer User and Group builders)

**Comment by CyB3RC0nN0R** [comment]
You can look into `envoy.data.MessageBuilder` from `envoy-common` for inspiration.

**Comment by CyB3RC0nN0R** [comment]
I think this isn't worth it. The objects are mutable and can be initialized using setters.
