### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-server-standalone#4]
Login still needs to be created as the current system may be helpful for developing, 
however it is not adapted to user needs.

**Comment by CyB3RC0nN0R** [comment]
A rather simple login mechanism could work by storing a password hash in the server database. When a new client opens a connection, they have to identify themselves by sending their user name and password hash.

This is obviously not secure in the sense of preventing a man-in-the-middle-attack, but can be augmented by the use of a secure connection. Java provides the `SSLEngine` class for this.
